
FROM debian

RUN apt-get update \
&& apt-cache search wget \
&& apt-get install -y wget \
&& apt-get install -y bzip2 \
&& useradd -ms /bin/bash teamspeak

USER teamspeak
WORKDIR /home/teamspeak/

RUN wget http://dl.4players.de/ts/releases/3.0.12.3/teamspeak3-server_linux_amd64-3.0.12.3.tar.bz2 \
&& tar xvf teamspeak3-server_linux_amd64-3.0.12.3.tar.bz2 \
&& rm teamspeak3-server_linux_amd64-3.0.12.3.tar.bz2 \
&& cd teamspeak3-server_linux_amd64 

WORKDIR /home/teamspeak/teamspeak3-server_linux_amd64 
CMD ["/bin/bash"]
# ENTRYPOINT ["./ts3server_minimal_runscript.sh createinifile=1"]
