
FROM debian

RUN apt-get update \
&& apt-get wget && useradd -ms /bin/bash teamspeak

USER teamspeak
WORKDIR /home/teamspeak

RUN wget http://dl.4players.de/ts/releases/3.0.12.3/teamspeak3-server_linux_amd64-3.0.12.3.tar.bz2 \
&& tar xjf teamspeak3-server_linux_amd64-3.0.12.3.tar.bz2 \
&& rm teamspeak3-server_linux_amd64-3.0.12.3.tar.bz2 \
&& cd teamspeak3-server_linux_amd64 

ENTRYPOINT ["./ts3server_minimal_runscript.sh createinifile=1"]
# && adduser teamspeak \
# && su teamspeak \
# && cd /home/teamspeak \
# && wget http://dl.4players.de/ts/releases/3.0.12.3/teamspeak3-server_linux_amd64-3.0.12.3.tar.bz2 \
# && tar xjf teamspeak3-server_linux_amd64-3.0.12.3.tar.bz2 \
# && rm teamspeak3-server_linux_amd64-3.0.12.3.tar.bz2 \
# && cd teamspeak3-server_linux_amd64 \
# && ./ts3server_minimal_runscript.sh createinifile=1 \
# && cd
